FROM golang:1.18
ENV CGO_ENABLED 0

RUN go install github.com/go-delve/delve/cmd/dlv@v1.8.3
RUN go install github.com/cespare/reflex@latest
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
RUN cp migrate.linux-amd64 /usr/local/bin/migrate

