version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ks
      POSTGRES_USER: ks
      POSTGRES_DB: ks

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    # image: cossacklabs/ci-py-go-themis
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    container_name: ks_api
    working_dir: /home/golang/app
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/golang/app:delegated
      - go:/home/user/gopath
    ports:
      - "9000:9000"
      - "9001:9001"
    # command: sh -c "cd functions/ksapi && gow run cmd/main.go"
    command: sh -c "gow run functions/ksapi/cmd/main.go"

volumes:
  db_data: {}
  go: {}
