name: keystone-cli # you probably want to 'snapcraft register <name>'
base: core20
version: "0.1"
summary: One app for managing your secrets # 79 char long summary
description: |
  Manage secrets got your projects in one place.
confinement: strict
plugs:
  config-fs:
    interface: system-files
    read:
    - /home/

apps:
  ks:
    command: bin/ks
    environment:
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - network-bind
      - network
      - config-fs

parts:
  ks:
    plugin: go
    override-build: |
      eval "$(cat variables)"
      rm -rf themis/
      git clone https://github.com/cossacklabs/themis.git
      make -C themis
      make install -C themis
      rm -rf themis/
      go mod edit -dropreplace github.com/wearedevx/keystone/api
      make build
      chmod +x ks
    build-packages: [make, git, libssl-dev]
    organize:
      /usr/local/lib: /lib/
      ../build/ks: /bin/ks
    source: .
