name: keystone-cli # you probably want to 'snapcraft register <name>'
base: core20
version: "0.1"
summary: One app for managing your secrets # 79 char long summary
description: |
  Manage secrets got your projects in one place.
confinement: classic

apps:
  ks:
    command: bin/ks

parts:
  ks:
    plugin: go
    override-build: |
      eval "$(cat variables)"
      rm -rf themis/
      git clone https://github.com/cossacklabs/themis.git
      make -C themis
      make install -C themis
      rm -rf themis/
      go mod edit -dropreplace github.com/wearedevx/keystone/api
      make build
      chmod +x ks
    build-packages: [make, git, libssl-dev]
    organize:
      /usr/local/lib: /lib/
      ../build/ks: /bin/ks
    source: .
