// require('./pull.spec.js')
// require('./init.spec.js')
// require('./invite.spec.js')
// require('./add.spec.js')
// require('./login.spec.js')
// require('./env.spec.js')
// require('./push.spec.js')
// require('./logout.spec.js')
// require('./delete.spec.js')
require('./share.spec.js')
