require('./utils/mock')
const { prepareEnvironment } = require('./utils')
const fs = require('fs')
const uuid = require('uuid/v4')
const pathUtil = require('path')
const { writeFileToDisk } = require('@keystone.sh/core/lib/file')
const { stdin } = require('mock-stdin')

const PullCommand = require('../commands/pull')
const InviteCommand = require('../commands/invite')
const AddCommand = require('../commands/add')
const PushCommand = require('../commands/push')
const DeleteCommand = require('../commands/delete')

const { login, logout, runCommand, addMemberToEnv } = require('./utils/helpers')
const { createDescriptor } = require('./utils')
jest.mock('../lib/blockstackLoader')
jest.mock('../lib/commands')

const fsp = fs.promises

describe('Push Command', () => {
  let result

  let io

  const keys = {
    up: '\x1B\x5B\x41',
    down: '\x1B\x5B\x42',
    enter: '\x0D',
    space: '\x20',
  }

  io = stdin()

  beforeEach(() => {
    // catch everything on stdout
    // and put it in result
    result = []
    jest.spyOn(process.stdout, 'write').mockImplementation(val => {
      fs.appendFile('unit-test.log', val)
      result.push(val)
    })
  })

  afterEach(() => jest.restoreAllMocks())

  it('should not update any files because same version', async () => {
    await prepareEnvironment()
    await login()

    await runCommand(PullCommand)

    const pulledFile = result.find(
      log => log.indexOf('You are already up to date') > -1
    )
    expect(pulledFile).toBeDefined()
  })

  it('should pull a file pushed by another user', async () => {
    // /!\ This one is a huge test. It rely on a lot of other commands than pull but decribe a common workflow between two member in a project
    await prepareEnvironment()
    await login(2)
    await login()
    //add other member ot the environment
    const interval = setInterval(() => {
      if (result.find(log => log.indexOf(`What's your email address?`) > -1)) {
        const sendKeystrokes = async () => {
          io.send(keys.enter)
        }
        setTimeout(() => sendKeystrokes().then(), 500)
        clearInterval(interval)
      }
    }, 500)
    const username = 'keystone_test2.id.blockstack'
    // Invite another usr and add them to the project so they can push files
    await runCommand(InviteCommand, ['keystone_test2@keystone.shh'])
    await runCommand(AddCommand, [username, 'keystone_test2@keystone.shh'])
    const projects = fs
      .readFileSync(
        pathUtil.join(
          __dirname,
          './hub/',
          `keystone_test1.id.blockstack--projects.json`
        )
      )
      .toString()

    // Create file normally generated by keystone web app
    fs.writeFileSync(
      pathUtil.join(__dirname, './hub/', `${username}--projects.json`),
      projects
    )
    await addMemberToEnv({ username })

    // Log in as user two
    await login(2)
    await runCommand(PullCommand)

    const uid = uuid()
    // Create a descriptpor and push it as user 2
    const fileDescriptor = createDescriptor({ content: uid })
    await writeFileToDisk(fileDescriptor)
    await runCommand(PushCommand, [pathUtil.join(fileDescriptor.name)])
    await logout()

    // Login as user 1 and pull file pushed by user 2
    await login()

    await runCommand(PullCommand)

    const content = (
      await fsp.readFile(pathUtil.join(__dirname, 'local/foo.txt'))
    ).toString()

    expect(uid).toEqual(content)
  })

  // fit('should update a file from because newer version on storage', async () => {
  //   await login()
  //   let fileToChange
  //   let envDescriptorToChange
  //   const files = fs.readdirSync(path.join(__dirname, './hub'))

  //   files.forEach(file => {
  //     if (file.indexOf('foo.txt') > -1) {
  //       fileToChange = path.join(__dirname, './hub/', file)
  //     }
  //     if (file.indexOf('default|') > -1) {
  //       envDescriptorToChange = path.join(__dirname, './hub/', file)
  //     }
  //   })

  //   const fileDescriptor = JSON.parse(fs.readFileSync(fileToChange))
  //   const envDescriptor = JSON.parse(fs.readFileSync())
  //   const newFileDescriptor = {
  //     ...fileDescriptor,
  //     version: fileDescriptor.version + 1,
  //     content: `${fileDescriptor.content} quu`,
  //   }

  //   console.log('FILE DESCRIPTOR', newFileDescriptor)
  //   return

  //   fs.writeFileSync(fileToChange, JSON.stringify(newFileDescriptor))

  //   await runCommand(PullCommand)

  //   const pulledFile = result.find(
  //     log => log.indexOf('You are already up to date') > -1
  //   )

  //   expect(pulledFile).toBeDefined()
  // })
})
