name: keystone-cli # you probably want to 'snapcraft register <name>'
base: core20
version: <%BRANCH%>
summary: One app for managing your secrets # 79 char long summary
description: |
  Manage secrets got your projects in one place.
confinement: strict

apps:
  ks:
    command: bin/ks
    environment:
      HOME: "$SNAP_USER_COMMON"
    plugs:
      - network-bind
      - network
      - home

parts:
  ks:
    plugin: go
    build-environment:
      - KSAPI_URL: <%KSAPI_URL%>
      - AUTH_PROXY: <%AUTH_PROXY%>
      - VERSION: <%VERSION%>
      - GITHUB_CLIENT_ID: <%GITHUB_CLIENT_ID%>
      - GITHUB_CLIENT_SECRET: <%GITHUB_CLIENT_SECRET%>
      - GITLAB_CLIENT_ID: <%GITLAB_CLIENT_ID%>
      - GITLAB_CLIENT_SECRET: <%GITLAB_CLIENT_SECRET%>
    override-build: |
      rm -rf themis/
      git clone https://github.com/cossacklabs/themis.git
      make -C themis
      make install -C themis
      rm -rf themis/

      make build -C cli
      chmod +x cli/ks
      ls

    build-packages: [make, git, libssl-dev]
    organize:
      /usr/local/lib: /lib/
      ../build/cli/ks: /bin/ks
    source: .
