# action.yml
name: 'compile with themis'
description: 'Greet someone and record the time'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
