version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ks
      POSTGRES_USER: ks
      POSTGRES_DB: ks
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    depends_on:
      - db
    # image: cossacklabs/ci-py-go-themis
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    container_name: ks_api
    working_dir: /home/golang/app
    environment:
      - DATABASE_URL=postgres://ks:ks@db:5432/ks?sslmode=disable
      - JWT_SALT=aaP|**P1n}1tqWK
    volumes:
      - ./:/home/golang/app:delegated
      - go:/home/user/gopath
    ports:
      - "9001:9001"
      # - "9000:9000"
    # command: sh -c "cd functions/ksapi && gow run cmd/main.go"
    command: sh -c "go get -u github.com/mitranim/gow && gow run main.go"

volumes:
  db_data: {}
  go: {}
