name: Keystone Deployement

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: keystone-server
  REGION: europe-west6

on:
  push:
    branches:
      - develop
      
jobs:
  ####################
  # Tests and checks #
  ####################
  end-to-end-tests:
    runs-on: ubuntu-20.04

    steps:
    # Get values for cache paths to be used in later steps
      - id: go-cache-paths
        run: |-
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Checkout the head ref instead of the PR branch that github creates.
          ref: ${{ github.head_ref }}

      # Cache go build cache, used to speedup go test.
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install themis
        run: |-
          wget -qO - https://pkgs-ce.cossacklabs.com/gpg | sudo apt-key add -
          sudo apt install apt-transport-https
          sudo sh -c 'echo "deb https://pkgs-ce.cossacklabs.com/stable/ubuntu focal main" >  /etc/apt/sources.list.d/themis.list'
          sudo apt update
          sudo apt install libthemis-dev

      - name: Run End-to-end Tests
        run: |-
          cd cli
          ./test.sh ./tests/...

  #####################
  # Server deployment #
  #####################
  deploy-server:
    needs: end-to-end-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          region: ${{ env.REGION }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          echo ${{ secrets.PROJECT_ID }}
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{  github.sha }} ./api/
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{  github.sha }}
          
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: ${{ secrets.SERVICE }}
          image: gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE }}:${{  github.sha }}
          region: ${{ env.REGION }}
          no_traffic: true
          tag: develop
          env_vars: JWT_SALT=${{ secrets.JWT_SALT }},DB_HOST=${{ secrets.DB_HOST }},DB_NAME=${{ secrets.DB_NAME}},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},CLOUDSQL_INSTANCE=${{ secrets.CLOUDSQL_INSTANCE }},CLOUDSQL_CREDENTIALS=${{ secrets.CLOUDSQL_CREDENTIALS }}
          flags: --allow-unauthenticated --add-cloudsql-instances ${{ secrets.CLOUDSQL_INSTANCE }} --service-account=${{ secrets.KS_SERVER_SERVICE_ACCOUNT }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

  #####################
  # Cli deployment #
  #####################
  
  snapcraft:
    runs-on: ubuntu-20.04
    needs:
      - end-to-end-tests
      - deploy-server
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cli
          go mod edit -dropreplace github.com/wearedevx/keystone/api
          sh deploy/gen_snapcraft.sh
        env:
          KSAPI_URL: ${{ secrets.KSAPI_URL_DEV }}
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID_DEV }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET_DEV }}
          GITLAB_CLIENT_ID: ${{ secrets.GL_CLIENT_ID }}
          GITLAB_CLIENT_SECRET: ${{ secrets.GL_CLIENT_SECRET }}
          BRANCH: develop
      - run: |
          sudo apt install libvshadow-utils
      - uses: snapcore/action-build@v1.0.8
        id: snapcraft
        with:
          path: cli/
      - run: |
          unsquashfs ${{ steps.snapcraft.outputs.snap }}
          snapcraft pack ./squashfs-root -o  ${{ steps.snapcraft.outputs.snap }}
      - uses: actions/upload-artifact@v2
        with:
          name: ks-snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge

  homebrew:
    runs-on: ubuntu-latest
    needs:
      - end-to-end-tests
      - deploy-server
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wearedevx/homebrew-keystone
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Run Template
        env:
          KS_API_URL: ${{ secrets.KSAPI_URL_DEV }}
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID_DEV }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET_DEV }}
          GITLAB_CLIENT_ID: ${{ secrets.GL_CLIENT_ID }}
          GITLAB_CLIENT_SECRET: ${{ secrets.GL_CLIENT_SECRET }}
          BRANCH: develop
        run: |-
          ./run_release.sh
      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula/keystone.rb'
          branch: 'main'
          default_author: 'github_actions'
          message: 'release develop'
