name: Keystone tests

on:
  push:
    branches:
      - ci-with-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          # Checkout the head ref instead of the PR branch that github creates.
          ref: ${{ github.head_ref }}
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v1
