name: Keystone tests

on:
  push:
    branches:
      - ci-with-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          # Checkout the head ref instead of the PR branch that github creates.
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-go@v2
        with:
          go-version: "^1.15" # The Go version to download (if necessary) and use.
      - name : "Install themis"
        run: |
          wget -qO - https://pkgs-ce.cossacklabs.com/gpg | sudo apt-key add -
          apt install apt-transport-https
          echo "deb https://pkgs-ce.cossacklabs.com/stable/ubuntu focal main" >  /etc/apt/sources.list.d/themis.list
          apt update
          apt install libthemis-dev
      - name: start test
        run: |
          ./test.sh ./...
