name: Release Binaries
on:
  push:
    branches:
      - develop
      - master

jobs:
  snapcraft:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cli
          go mod edit -dropreplace github.com/wearedevx/keystone/api
      - run: |
          sudo apt install libvshadow-utils
      - run: |
          # create variables file
          cd cli
          echo 'export KSLDFLAGS=" -X github.com/wearedevx/keystone/cli/pkg/client.ApiURL=${{ secrets.KSAPI_URL_DEV }}"' > variables
      - uses: snapcore/action-build@v1.0.8
        id: snapcraft
        env:
          KSLDFLAGS: -X github.com/wearedevx/keystone/cli/pkg/client.ApiURL=${{ secrets.KSAPI_URL_DEV }}
        with:
          path: cli/
      - run: |
          unsquashfs ${{ steps.snapcraft.outputs.snap }}
          snapcraft pack ./squashfs-root -o  ${{ steps.snapcraft.outputs.snap }}
      - uses: actions/upload-artifact@v2
        with:
          name: ks-snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge

  macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wearedevx/homebrew-keystone
      - name: Run Template
        env:
          KS_API_URL: ${{ secrets.KSAPI_URL_DEV }}
          BRANCH: develop
        run: |-
          ./run_release.sh
      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula/keystone.rb'
          default_author: 'github_actions'
          message: 'release develop'
