name: Release Binaries
on:
  push:
    branches:
      - develop
      - master

jobs:
  snapcraft:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd cli
          go mod edit -dropreplace github.com/wearedevx/keystone/api
          sh deploy/gen_snapcraft.sh
        env:
          KSAPI_URL: ${{ secrets.KSAPI_URL_DEV }}
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID_DEV }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET_DEV }}
          GITLAB_CLIENT_ID: ${{ secrets.GL_CLIENT_ID }}
          GITLAB_CLIENT_SECRET: ${{ secrets.GL_CLIENT_SECRET }}
          BRANCH: develop
      - run: |
          sudo apt install libvshadow-utils
      - uses: snapcore/action-build@v1.0.8
        id: snapcraft
        with:
          path: cli/
      - run: |
          unsquashfs ${{ steps.snapcraft.outputs.snap }}
          snapcraft pack ./squashfs-root -o  ${{ steps.snapcraft.outputs.snap }}
      - uses: actions/upload-artifact@v2
        with:
          name: ks-snap
          path: ${{ steps.snapcraft.outputs.snap }}
      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge

  macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wearedevx/homebrew-keystone
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
      - name: Run Template
        env:
          KS_API_URL: ${{ secrets.KSAPI_URL_DEV }}
          GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID_DEV }}
          GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET_DEV }}
          GITLAB_CLIENT_ID: ${{ secrets.GL_CLIENT_ID }}
          GITLAB_CLIENT_SECRET: ${{ secrets.GL_CLIENT_SECRET }}
          BRANCH: develop
        run: |-
          ./run_release.sh
      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula/keystone.rb'
          branch: 'main'
          default_author: 'github_actions'
          message: 'release develop'
