name: Keystone tests

on:
  push:
    branches:
      - ci-with-test

jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: cossacklabs/ci-py-go-themis

    steps:
      - uses: actions/checkout@v1
        with:
          # Checkout the head ref instead of the PR branch that github creates.
          ref: ${{ github.head_ref }}
      # - name: Use go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: "^1.15" # The Go version to download (if necessary) and use.
      # - name: Hello world action step
      #   id: hello
      #   uses: actions/hello-world-docker-action@v1
      - name: start test
        run: |
          GOCACHE="./" LDFLAGS="-X github.com/wearedevx/keystone/pkg/client.ksauthURL=http://localhost:9000 -X github.com/wearedevx/keystone/pkg/client.ksapiURL=http://localhost:9001" go test -tags test -ldflags "$LDFLAGS" -work "$@"
