name: Keystone tests

on:
  push:
    branches:
      - ci-with-test

jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: cossacklabs/ci-py-go-themis

    steps:
      - name: Create cache folder
        run: |
          mkdir -p /home/user/.gocache
          mkdir -p /home/user/.gomodcache
          mkdir -p /home/user/.tmp
          mkdir -p /home/user/.home/.config

    # Get values for cache paths to be used in later steps
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::/home/user/.gocache"
          echo "::set-output name=go-mod::/home/user/.gomodcache"

      - uses: actions/checkout@v1
        with:
          # Checkout the head ref instead of the PR branch that github creates.
          ref: ${{ github.head_ref }}

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: ls -al
        run: |
          ls -al

      - name: start test
        run: |
          cd functions/ksauth
          GOCACHE="/home/user/.gocache" TMPDIR="/home/user/.tmp" go run -tags test cmd/main.go &
          cd ../..
          HOME=/home/user/.home TMPDIR="/home/user/.tmp" GOCACHE="/home/user/.gocache" go test -tags test -ldflags "-X github.com/wearedevx/keystone/pkg/client.ksauthURL=http://localhost:9000 -X github.com/wearedevx/keystone/pkg/client.ksapiURL=http://localhost:9001" -work ./tests/login-test/login_test.go -v
