name: use-keystone-action

on: [push]

jobs:
  use_keystone-action:
    runs-on: ubuntu-latest
    name: A job to make keystone-ci usable secrets
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load Secrets
        uses: wearedevx/keystone-action@feat/read-message
        id: load_secrets
        with:
          token: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          # Normally, we would use
          keystone_slot_1: ${{ secrets.KEYSTONE_PROD_SLOT_1 }}
          keystone_slot_2: ${{ secrets.KEYSTONE_PROD_SLOT_2 }}
          keystone_slot_3: ${{ secrets.KEYSTONE_PROD_SLOT_3 }}
          keystone_slot_4: ${{ secrets.KEYSTONE_PROD_SLOT_4 }}
          keystone_slot_5: ${{ secrets.KEYSTONE_PROD_SLOT_5 }}
      - name: Show Secrets
        id: show_secrets
        run: |
          echo "From env action context: ${{ env.TEST }}"
          echo "From runner job environment variables $TEST"

      - name: Test there is a file
        id: test_file
        run: |
          F="ks_temp/test.txt";

          if [ -f $F ]; then
            echo "$F exists";
            C=`cat $F`;
            echo $C;

            if [ "$C" == "Ceci est un test" ]; then
              echo "It has the right content";
            else
              echo "File value is not right";
              exit 1;
            fi
          else
            echo "$F does not exits";
            exit 1;
          fi

