name: Keystone tests

on:
  push:
    branches:
      - ci-with-test

jobs:
  my-job:
    runs-on: ubuntu-20.04

    # container:
    #   image: cossacklabs/ci-py-go-themis

    steps:
      # - name: Create cache folder
      #   run: |
      #     mkdir -p /home/user/.gocache
      #     chmod -R 777 /home/user/.gocache
      #     mkdir -p /home/user/.gomodcache
      #     chmod -R 777 /home/user/.gomodcache
      #     mkdir -p /home/user/.tmp
      #     chmod -R 777 /home/user/.tmp
      #     mkdir -p /home/user/.home/.config
      #     chmod -R 777 /home/user/.home/.config
      #     sudo mkdir -p /__w/_temp/
      #     sudo chmod -R 777 /__w/_temp/

    # Get values for cache paths to be used in later steps
      # - id: go-cache-paths
      #   run: |
      #     echo "::set-output name=go-build::/home/user/.gocache"
      #     echo "::set-output name=go-mod::/home/user/.gomodcache"

      - uses: actions/checkout@v1
        with:
          # Checkout the head ref instead of the PR branch that github creates.
          ref: ${{ github.head_ref }}

      # Cache doesn't seem to work.
      # We alaways see : go download...
      # Cache go build cache, used to speedup go test
      # - name: Go Build Cache
      #   id: go-build-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: /home/user/.gocache
      #     key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      # - name: Go Mod Cache
      #   id: go-mod-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: /home/user/.gomodcache
      #     key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      # - name: is go-mod cached?
      #   run: echo "go-mod CACHE OK"
      #   if: steps.go-mod-cache.outputs.cache-hit == 'true'

      # - name: is go-mod not cached?
      #   run: echo "go-mod CACHE KO"
      #   if: steps.go-mod-cache.outputs.cache-hit != 'true'

      # - name: is go-build cached?
      #   run: echo "go-build CACHE OK"
      #   if: steps.go-build-cache.outputs.cache-hit == 'true'

      # - name: is go-build not cached?
      #   run: echo "go-build CACHE KO"
      #   if: steps.go-build-cache.outputs.cache-hit != 'true'


      # - name: start test
      #   run: |
      #     cd functions/ksauth
      #     GOMODCACHE="/home/user/.gomodcache" GOCACHE="/home/user/.gocache" TMPDIR="/home/user/.tmp" go run -tags test cmd/main.go &
      #     cd ../ksapi
      #     GOMODCACHE="/home/user/.gomodcache" GOCACHE="/home/user/.gocache" TMPDIR="/home/user/.tmp" go run -tags test cmd/main.go &
      #     cd ../..
      #     GOMODCACHE="/home/user/.gomodcache" GOCACHE="/home/user/.gocache" HOME=/home/user/.home TMPDIR="/home/user/.tmp" go test -tags test -ldflags "-X github.com/wearedevx/keystone/pkg/client.ksauthURL=http://localhost:9000 -X github.com/wearedevx/keystone/pkg/client.ksapiURL=http://localhost:9001" -work ./... -v

      - name : "Install themis"
        run: |
          wget -qO - https://pkgs-ce.cossacklabs.com/gpg | sudo apt-key add -
          sudo apt install apt-transport-https
          sudo sh -c 'echo "deb https://pkgs-ce.cossacklabs.com/stable/ubuntu focal main" >  /etc/apt/sources.list.d/themis.list'
          sudo apt update
          sudo apt install libthemis-dev
      - name: start test
        run: |
          ./test.sh ./...
